### ISSUE TITLE
Need ability to login on sites like webnovel to get unlocked chapter 

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#102]
Webnovel.com has launched subscription based user on its site so subscriber user can get all chapter unlocked. Maybe we need ability to login using username and password in webnovel.com crawler to get unlocked chapter. Preferable in console bot because of security concern

**Comment by dipu-bd** [comment]
I tried it at the beginning. But it is too complicated. Webnovel has both social based login and email based one. I doubt many users use email based one. 

Additionally, the spirit stones requires money to buy. Most people won't want to give access to their account to some third party app because there is a risk of losing their precious stones.

**Comment by yudilee** [comment]
Agree with you, for now i will close this issue. Thanks for info

**Comment by BobbyWibowo** [comment]
Aw darn, too bad. I'm actually one of those few users with email logins.

**Comment by nightcrawler123** [comment]
Me too I too have email-based login
