### ISSUE TITLE
Feature Request : enable search on selected source

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/lightnovel-crawler#109]
Hi @dipu-bd ,

New search method is really amazing. I think, i want deleted feature to enable search on selected source  back. If i need to search only on selected source, isn't it going to be much faster for some slow source such as novel planet. Also if search result only show one source can we automatically show info too. It can also help while testing new search method(while adding it to crawler). Thank you

**Comment by dipu-bd** [comment]
I have kept that option too. You can pass `--sources` to enable the source selection menu. I just did not display it by default, because there are a lot of sources now. Showing them all at once is distracting and bothersome. I am thinking of a better way to do this before making a release of new version.

**Comment by yudilee** [comment]
wow. that great. i will try add it in telegram bot

**Comment by dipu-bd** [comment]
Oh, I forgot. I replaced the old code of telegram bot and removed source selection feature. Wait a bit, I will make push soon to bring it back
