### ISSUE TITLE
Implement cmdline arg --chapters

### ISSUE THREAD

**Issue by dbosst** [dipu-bd/lightnovel-crawler#130]
The command line argument `--chapters` doesn't seem to work because it seems it's not actually implemented in the code.

This is very useful for me and probably other people that just want to every day copy the URLs for all the chapters from their current list of webnovels they are reading, and hopefully conveniently put them in a single epub.

**Comment by dipu-bd** [comment]
Thanks for reporting. I will be working on it soon

**Comment by dipu-bd** [comment]
It works, but you must pass the novel page url. Examples:
`lncrawl -s https://www.wuxiaworld.com/novel/against-the-gods  --chapters https://www.wuxiaworld.com/novel/against-the-gods/atg-chapter-1   https://www.wuxiaworld.com/novel/against-the-gods/atg-chapter-6   https://www.wuxiaworld.com/novel/against-the-gods/atg-chapter-8`

You have to input the source url because there is no way to know which novel to get the chapters from. And you can only pass urls from a single novel source at a time.

**Comment by dbosst** [comment]
In case anyone needs it...
[ here is a hacky fork to do what I wanted above](https://github.com/dbosst/lightnovel-crawler/tree/chapters)

Read the commit message for how to.

**Comment by dipu-bd** [comment]
Based on what I understand from your commit, this may not always work. It is not always possible to directly get the novel page url from the chapter url. And without the novel-page url, a crawler can not be initialized.

I have added an issue #133 to support this here. This may take some time, but it will be available in the near future.

**Comment by dbosst** [comment]
Of course I am just using it on a few websites at the moment every day like boxnovel / wuxiaworld
