### ISSUE TITLE
Download slows down on long novels

### ISSUE THREAD

**Issue by Galunid** [dipu-bd/lightnovel-crawler#1306]
When downloading long novels, download speed slows down very noticeably. It goes from ~13 chapters/s to 0.5 chapter/s. Source seems irrelevant

**App source**:    build it myself
**App version**:   latest dev branch
**Your OS**:       Linux

**Comment by dipu-bd** [comment]
Download speed greatly depends on your network connection. When many concurrent requests performed to same server, it becomes slower over time. It is because every single TCP packets hops through many nodes to reach your PC. Normally max size of a TCP packet is 64KB. Many many TCP packets needs to reach you successfully to download a novel with a lots of chapters.

CPU and RAM speed is the next suspect. In that case we need to do some profiling to check if there is any memory leak which is slowing down the download speed.

**Comment by dipu-bd** [comment]
This should improve after 2.30.0
