### ISSUE TITLE
Fix this source : webnovel.com

### ISSUE THREAD

**Issue by thescz** [dipu-bd/lightnovel-crawler#1362]
## Let us know

**Novel URL**:   https://www.webnovel.com/book/my-three-wives-are-beautiful-vampires._20553633305398405)
**App Location**:   /Users/thescz/Library/Python/3.8/bin/lncrawl
**App Version**:   v2.31.0

## Describe this issue

Whenever I try to download any story from Webnovel, it says 0 volumes and 0 chapters found. This occurs with every story on the site. 

![image](https://user-images.githubusercontent.com/106260730/170295612-1b8e15ac-9804-45b4-8163-665e3ad2be6f.png)

**Comment by RomuloPS** [comment]
Example of the new response on their api:

[/get-chapter-list](https://www.webnovel.com/go/pcm/chapter/get-chapter-list?_csrfToken=2e6ea907-f31e-41f3-9162-635e2c166e36&bookId=20553633305398405&pageIndex=0&encryptType=1&_=1653584485676)

Apparently people on the qidian underground discord have figured out the encryption already, if someone wants to talk to them. Their stuff is not open source, so I don't have their code.

**Comment by budikesuma** [comment]
> Example of the new response on their api:
> 
> [/get-chapter-list](https://www.webnovel.com/go/pcm/chapter/get-chapter-list?_csrfToken=2e6ea907-f31e-41f3-9162-635e2c166e36&bookId=20553633305398405&pageIndex=0&encryptType=1&_=1653584485676)
> 
> Apparently people on the qidian underground discord have figured out the encryption already, if someone wants to talk to them. Their stuff is not open source, so I don't have their code.

If you think there are the encryption code on the QI site, you are completely wrong, the real encryption is on the wuxiaworld.com site.  until now various scrapers out there have not managed to solve it.  But for this QI site it only uses the merging/joining method between paragraph ids.  It's very easy to solve.  

I can use manual scripts to combine those id paragraphs into one whole chapter.  Maybe you can give me a QI novel link to try out.

**Comment by mesmerlord** [comment]
@budikesuma I think they're talking about 
![image](https://user-images.githubusercontent.com/76161333/170890024-a53fe58b-e05a-4368-95be-f39f683d88b0.png)

It seems to be only on the recently added chapters

**Comment by budikesuma** [comment]
> chapters

@mesmerlord 

Decoding...?, I don't see the need for that. 
Because I can normally scrape free chapters from webnovel sites.

Indeed, my method only uses userscript flows, by detecting the id of each paragraph, then combining all paragraphs into one whole chapter. 

My scripts is also able to get all the necessary metadata including the translator's name if any, the main genre as well as the reader's preferred genres.

Since you said it might be from recent novels, I tried many new novels. There is no such problem.

I'll show you one of the latest novels that was just updated on webnovel a few hours ago.

Since GitHub does not support `.epub` files, I changed the file name to `.zip`, please change it back to `.epub`.
.
.
[Immortal Universe.epub.zip](https://github.com/dipu-bd/lightnovel-crawler/files/8805717/Immortal.Universe.epub.zip)

`with my font files removed`
.
.
![Screenshot_20220531-204700_QuickEdit](https://user-images.githubusercontent.com/50254552/171190339-90c8cf6c-86fd-49d7-8c89-9d188bbb411a.jpg)
.
.
![Screenshot_20220531-194725_MiXplorer](https://user-images.githubusercontent.com/50254552/171190471-c5d3c7ba-f0d1-4bcb-a05a-7dab0d75e177.jpg)

**Comment by dipu-bd** [comment]
Latest changes to webnovel made it pretty harder to crawl. They are using a webassembly code to decrypt the response content. I have checked it and found it quite bothersome to deal with. It can not be solved easily in a small amount of time. 

There are lots of other alternate sources where the same novels can be found. I do not see any point bothering with webnovel. Adding it to the rejected sources.
