### ISSUE TITLE
How to download wattpad paid stories?

### ISSUE THREAD

**Issue by Digital-XxX** [dipu-bd/lightnovel-crawler#1407]
Does logging in with premium account will solve this problem?

**Comment by dipu-bd** [comment]
wattpad does not support login

**Comment by Digital-XxX** [comment]
So we can only download free stories?

**Comment by dipu-bd** [comment]
For now, yes. We just need to add the login feature to wattpad crawler. I've changed this issue type to a feature request.

**Comment by dipu-bd** [comment]
now wattpad supports login

**Comment by tycoonlover1359** [comment]
I know this is a closed issue, but might I suggest some changes:

1. Line `39`, change:
```python
if email != data['username']:
```
to
```python
if email.lower() != data['username'].lower:
```

(The check makes both into lowercase strings so case sensitivity can be ignored.)

The reasoning behind this is that Wattpad usernames for login are case insensitive, so if you're like me and your username on Wattpad is officially `Tycoonlover1359` (note the uppercase `T`) but your login in your password manager is noted as `tycoonlover1359` (note the lowercase `t`), then this check fails despite having successfully logged in.

2. line `40`, change:
```python
print('Logged in as %s[%s]<%s>' % data['name'], data['username'], data['email'])
```
to
```python
 print('Logged in as %s[%s]<%s>' % (data['name'], data['username'], data['email']))
```

(The format string is now provided a tuple of arguments.)

In my testing, this line would otherwise raise a `TypeError: not enough arguments for format string` error, which makes sense as the first options is interpreted and run as 3 arguments to the print command, not a single string formatted with 3 arguments.

---

I have added these changes in a pull request, #1458
