### ISSUE TITLE
Bypass cloudflare | Selenium undetected-chromedriver

### ISSUE THREAD

**Issue by idMysteries** [dipu-bd/lightnovel-crawler#1484]
Maybe we can use phantomjs for these sites?

**Comment by dipu-bd** [comment]
I considered it before. But sadly PhantomJS is dead. 

Check https://github.com/ariya/phantomjs/issues/15344

**Comment by idMysteries** [comment]
Maybe Selenium?

https://stackoverflow.com/questions/53657215/running-selenium-with-headless-chrome-webdriver

**Comment by dipu-bd** [comment]
Adding selenium needs the webdriver requirement. It changes based on different browser and browser versions. It will be a headache to keep track of it. That's why I did not try to add it yet.

There is a solution however. We can use docker to run a fixed version of selenium browser and webdriver. Also we need to develop a request like interface to handle the connection to selenium. There are a lots of things to be changed. I have not tried to pick it up because of that.

**Comment by idMysteries** [comment]
Auto-update is possible
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/#tabs-2-1

**Comment by idMysteries** [comment]
In the parser code, it will be possible to do a check. If the driver is started, then parse the page through the driver. If the driver does not start, then use the old code

**Comment by dipu-bd** [comment]
Using selenium will be much slower than the plain request session. The crawler that needs to use it can have a separate flag and separate sets of read novel-info and download methods.

**Comment by idMysteries** [comment]
Let's put it off until better times. Qidian and WebNovel are not so important.

**Comment by dipu-bd** [comment]
True. There are lots of alternative sources. It is not worth the time to invest on supporting a headless browser for a couple of hard to crawl sources.

**Comment by idMysteries** [comment]
There is unique content on WebNovel, for which I wrote the new code.

**Comment by idMysteries** [comment]
@dipu-bd https://medium.com/@kcemenike/bypassing-cloudflare-restrictions-in-selenium-4-d3ed315af0e8
undetected_chromedriver doesn't work?

**Comment by dipu-bd** [comment]
Let's move this discussion on to more a general issue: #1559
