### ISSUE TITLE
https://wuxiaworld.eu

### ISSUE THREAD

**Issue by chiffonkla** [dipu-bd/lightnovel-crawler#2224]
- Language: English
- Supports Searching: Yes
- Contains Machine Translations: Yes/No
- Contains Manga/Manhua/Manhwa: No
- Has CloudFlare Protection: No

**Comment by camp00000** [comment]
The website redirects to https://wuxia.click/ which is already a supported source (and I tested it, seems to work just fine).
> https://github.com/dipu-bd/lightnovel-crawler/blob/master/sources/en/w/wuxiaclick.py

@dipu-bd close this issue?

**Comment by chiffonkla** [comment]
It said that it did not recognize the site https://www.wuxia.click or the Error: ('Fail to init crawler: %s is rejected', 'https://wuxia.click/') for https://wuxia.click/

**Comment by chiffonkla** [comment]
> The website redirects to https://wuxia.click/ which is already a supported source (and I tested it, seems to work just fine).
> 
> > https://github.com/dipu-bd/lightnovel-crawler/blob/master/sources/en/w/wuxiaclick.py
> 
> 
> 
> @dipu-bd close this issue?

It said that it did not recognize the site https://www.wuxia.click or the Error: ('Fail to init crawler: %s is rejected', 'https://wuxia.click/') for https://wuxia.click/

**Comment by camp00000** [comment]
> > The website redirects to https://wuxia.click/ which is already a supported source (and I tested it, seems to work just fine).
> > > https://github.com/dipu-bd/lightnovel-crawler/blob/master/sources/en/w/wuxiaclick.py
> > 
> > 
> > @dipu-bd close this issue?
> 
> It said that it did not recognize the site https://www.wuxia.click or the Error: ('Fail to init crawler: %s is rejected', 'https://wuxia.click/') for https://wuxia.click/
> 
> Discord bot could not find novels from there too.

@chiffonkla sorry for the slow reply but yes, the www.wuxia.click domain was not supported, only the wuxia.click domain.
I've remedied this in #2265 . 

It seems the reason why the bot refuses to download from there is because the wuxia.click domain is in the rejected sources list (see https://github.com/dipu-bd/lightnovel-crawler?tab=readme-ov-file#rejected-sources ). It was added to that list back in August of 2023, I will look into this.


Until it's removed from that list it seems the only way to download from there is to run the crawler locally on your own pc.
Keep an eye on #2265 for any updates.

**Comment by dipu-bd** [comment]
#2085
