### ISSUE TITLE
Colspan and Rowspan are removed

### ISSUE THREAD

**Issue by jere344** [dipu-bd/lightnovel-crawler#2285]
## Describe the bug

When parsing a table the column and row span are not preserved.
example : chapter 2 of https://www.royalroad.com/fiction/66553/chaos-guide

Source :
![image](https://github.com/dipu-bd/lightnovel-crawler/assets/86294972/051cb690-9f1f-465c-b30f-ffe435e872b7)
Download :
![image](https://github.com/dipu-bd/lightnovel-crawler/assets/86294972/6e294ac8-1a12-4cba-a230-3c015e37aa6d)

## Let us know

**App source**:    PIP
**App version**:   3.2.9
**Your OS**:       Linux

**Comment by camp00000** [comment]
Preserving those attributes doesn't lead to a significant change in visual output in this case unfortunately.
This is due to the fact that the centering of the "header" here is done via css class and not style element.

See this output here
![image](https://github.com/dipu-bd/lightnovel-crawler/assets/76262772/1cbb1ecf-cbd0-4e92-b024-c4c11f6ab8e0)
![image](https://github.com/dipu-bd/lightnovel-crawler/assets/76262772/a106f56d-07ef-4139-ba6b-ce4c7034622e)

**Comment by jere344** [comment]
I was thinking in general, not just for this source. If i'm not mistaken, we just pass the web page body to a function that extract text, table, paragraphs ... This is this generic function that I think should keep rowspans and columnspans when extracting tables.

That was just the first example I found, here it doesn't make that much of a difference, especially since we don't display borders.
But not preserving it means a table like this :
```
-----------------
| a | a | b | b |
-----------------
| a     | b     |
-----------------
```
Will become like this :
```
-----------------
| a | a | b | b |
-----------------
| a  | b        |
-----------------
```
This is still not a big change, but the more complicated the table, the worse it will look in the end.


Of course it is not a big priority, but I personally think it should be handled. I didn't have the time to look into it yet, but I can do it if other maintainers are busy or not interested.

**Comment by camp00000** [comment]
It got merged so I guess you can close the issue or reopen it if you end up finding an issue in how it handles certain tables.
