### ISSUE TITLE
 Request for Application: Format Choice for Output

### ISSUE THREAD

**Issue by AJ-PK** [dipu-bd/lightnovel-crawler#232]
I very much appreciate the application that you have made, but have been meaning to ask this for a long time is there a reason why the application doesn't give you a choice in the output format if you could make it so that you can request for a single format from the application that would be much appreciated.

**Comment by dipu-bd** [comment]
The `--format` option allows you to choose the output formats. But in console app, I did not show output selection because you can stop generating output anytime by pressing Ctrl+C and to reduce number of user interaction.

I see that either methods are not too intuitive. I plan to show format choice in the next version. It will be available from v2.17.0

**Comment by AJ-PK** [comment]
Thanks for the quick response and clarification seems like there was a solution just not one that I know of till now. 😓

**Comment by dipu-bd** [comment]
done. will be available from v2.17.0
