### ISSUE TITLE
Fix this source : faqwiki.us

### ISSUE THREAD

**Issue by zillafox** [dipu-bd/lightnovel-crawler#2423]
Yes

**Novel URL**:     https://www.faqwiki.us/novel/myst-might-mayhem/
**App Location**:    Discord
**App Version**:   Lightnovel Crawler
## Describe this issue
Failed to get queries for the novel chapters from faqwiki.us
![Screenshot_20240726-135805_Discord](https://github.com/user-attachments/assets/cae209bf-7a9b-4045-b504-a403c34a0578)

**Comment by camp00000** [comment]
@zillafox the issue was that although the source is supported, the domain with `www.` in front of it was not until now.
I've fixed that here: https://github.com/dipu-bd/lightnovel-crawler/pull/2424

And for now what you can do is supply the same link to the bot but remove the `www.` and it'll work just fine.

So in your case, just give the bot this link and it'll work: `https://faqwiki.us/novel/myst-might-mayhem/`

**Comment by zillafox** [comment]
> @zillafox the issue was that although the source is supported, the domain with `www.` in front of it was not until now. I've fixed that here: #2424
> 
> And for now what you can do is supply the same link to the bot but remove the `www.` and it'll work just fine.
> 
> So in your case, just give the bot this link and it'll work: `https://faqwiki.us/novel/myst-might-mayhem/`

Thanks Mate, i can confirm it works without pasting "www."
