### ISSUE TITLE
Feature request: Target filename

### ISSUE THREAD

**Issue by greenaar** [dipu-bd/lightnovel-crawler#267]
Would it be possible to add support for either naming the target, or stripping the chapter count?

While knowing how many chapters are in the file is valuable, there have been times I'd rather just have the title, especially when replacing an existing (older) file on a reader.

**Comment by dipu-bd** [comment]
It is a good idea. I will add an option to the console bot to specify the filename.

**Comment by dipu-bd** [comment]
I have added two new options:
```
  --filename NAME       Set the output file name
  --filename-only       Skip appending chapter range with file name
```

Using the first option, `--filename` you can specify a custom file name. example: `lncrawl --filename "My Novel Title"`

Pass the second option, `--filename-only` to stop automatically appending the chapter range after file name. example: `lncrawl --filename-only`. 

BUT BEWARE! `--filename-only` will set the name of the output files to `Trash of the Count s Family.epub` instead of `Trash of the Count s Family c20-30.epub`. Using `--multi` to split novels by volumes will not generate multiple output file.

----

These changes will be effective from the next version.
