### ISSUE TITLE
Chapter numbering issue

### ISSUE THREAD

**Issue by MMDF** [dipu-bd/lightnovel-crawler#345]
**Describe the bug**
This novel has volumes that all start their chapter numbering from 1. When the novel is downloaded, the chapter numbering confuses the program. The end result is that the first 8 chapters in the epub become the chapter 1's from all 8 volumes in order. The next 8 chapters become chapter 2's from all 8 volumes in order, you get the pattern.

**Let us know**
- Novel URL: https://lnmtl.com/novel/magic-industrial-empire
- App Version: 2.19.3
- Package: pip
- OS: Ubuntu on Windows [WSL]

**Comment by dipu-bd** [comment]
fixed by #355

**Comment by mhussaincov** [comment]
hi there sir Sudipto,
because I have installed lightnovel-crawler from pip, would it be
possible to have a version with these fixes released? or a location
where in I would be able to install the latest version of
lightnovel-crawler?
thank you,
Majid Hussain

On 04/03/2020, Sudipto Chandra <notifications@github.com> wrote:
> Closed #345.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dipu-bd/lightnovel-crawler/issues/345#event-3096148653


-- 
kind regards,
Majid Hussain

**Comment by dipu-bd** [comment]
I will publish new version soon after some testing.
