### ISSUE TITLE
https://totallytranslations.com/

### ISSUE THREAD

**Issue by XxJibril** [dipu-bd/lightnovel-crawler#458]

**Comment by SirGryphin** [comment]
Tried making source but keep getting a SSL error. Here is my file: 
[totallytranslations.zip](https://github.com/dipu-bd/lightnovel-crawler/files/6498635/totallytranslations.zip)


! Error: HTTPSConnectionPool(host='totallytranslations.com', port=443): Max retries exceeded with url: /category/peerless-martial-god-2/ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)')))
