### ISSUE TITLE
include function/parameter to bypass "Press Enter to exit"

### ISSUE THREAD

**Issue by jad0083** [dipu-bd/lightnovel-crawler#48]
I'm trying to integrate and automate using the windows version of the crawler.  when I try to batch out the executable, it stops after each execution due to the requirement for the "Enter" key to be pressed.  I tried the -f and --suppress flags, but execution still requires the "Enter" key press.  Adding this flag/parameter would help automation.

**Comment by yudilee** [comment]
have you try the python script instead of windows executable (i prefer script because easier to update) . I used the script and it run well, i mean the scheduled task automatically run the next task without needing "enter" key press. maybe it happen because the executable ask for it not the script behind it

**Comment by dipu-bd** [comment]
@jad0083 `--suppress` should suppress all inputs. I will publish a windows build in the next week. This issue will be fixed there. For now, you can use the python script as suggested by @yudilee

**Comment by jad0083** [comment]
Thanks guys!  Yes, the python script works without the Enter key requirement!  And thank you for getting this downstream to the windows binaries.

**Comment by dipu-bd** [comment]
Fixed in [lightnovel-crawler v2.7.2 for windows ~ 14.3MB](https://goo.gl/sc4EZh)
