### ISSUE TITLE
Fix worldnovel.online crawler

### ISSUE THREAD

**Issue by budikesuma** [dipu-bd/lightnovel-crawler#634]
Dear Devs, please update support for the site: 
https://www.worldnovel.online/
The problem is that the lightnovel-crawler fetches not just chapters but entire pages of the novel's website.
Thanks in advance.

**Comment by dipu-bd** [comment]
Okay I will check it out. Bugs always gets priority.

**Comment by SirGryphin** [comment]
It's because of this bit of code.

```
contents = soup.select_one(', '.join([
            '.post-content'
            '.cha-words',
            '.cha-content',
            '.chapter-fill',
            '.entry-content.cl',
            '#content',
```

The bit that gets content using "chapter-fill" also includes comments and all other stuff on chapters page. I think if that's removed and "post-content" is used instead it will work. The only problem is I just tried to test this and I'm getting this error.

` ! Error: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.`

**Comment by dipu-bd** [comment]
I removed `chapter-fill` from. But could not test because of cloudflare issue
