### ISSUE TITLE
Support on lnmtl and mtlnovel raw text

### ISSUE THREAD

**Issue by Balefirex** [dipu-bd/lightnovel-crawler#671]
Both lnmtl and mtlnovel have toggle-able access to the raw, with lnmtl giving the option to also disable the English translation. mtlnovel requires log-in to view the raw, and since lncrawler doesn't currently have log-in support for mtlnovel, lnmtl should probably be prioritized.

Essentially requesting the ability to toggle the raw and english on or off for when you parse lnmtl novels, which would give 3 options

1. Crawling with only the translation
2. Crawling with translation + raw
3. Crawling with only raw

**Comment by dipu-bd** [comment]
**Note: ** For this, we can add additional crawler to crawl raw only. Currently, only one to one relation is possible between a source link and crawler file. We can enable one to many relation by taking user input on which crawler to use for scraping.

**Comment by dipu-bd** [comment]
it seems this will take too much work. all the bots needs to be updated for this change. won't work on this for now

**Comment by Galunid** [comment]
Wouldn't it be possible to use `ruby` tags for raw? Toggling can be done by adding `ruby{ display: none;}` to stylesheets. This would basically solve points 1 and 2

**Comment by dipu-bd** [comment]
Currently the app only has one to one map from an URL to a crawler. For implementing support for both translation + raw, we have to use the same URL for crawlers. This is going to be an issue, since the entire architecture needs to be changed for console app, discord and telegram bots. In terminal, we would have to show a choice to select which crawler to use, on discord/telegram bots a question needs to be added to ask whether to download translation/raw/both. 

Since this requires changing current architecture in many different ways, I have put this away for now.
