### ISSUE TITLE
Not seeing all chapters of a webnovel >100 chapters on https://www.lightnovelworld.com/

### ISSUE THREAD

**Issue by Kjai88** [dipu-bd/lightnovel-crawler#714]
**Describe the bug**
lncrawl doesn't see all the chapters of a novel, only the first 100 chapters (which is the first page in the table of contents)

**Let us know**
- Novel URL: https://www.lightnovelworld.com/novel/ranker-who-lives-twice
- App Version: 2.24.1
- Package: exe
- OS: Windows 10
![image](https://user-images.githubusercontent.com/68389079/103943436-16d77180-5100-11eb-8097-d18a0201c810.png)

**Comment by SirGryphin** [comment]
I was having same issue, seem it's only fetching chapters from first page and not all pages. It because they change site slightly. I've committed the change in script to get it working but it can take while to get released. Also lightnovelworld.com is coming up with too many http requests error as well.

If you want to edit script yourself do this. In the python script you need to change these lines:

**FIND:**
`chapter_list_url = 'https://www.lightnovelworld.com/novel/%s?pageNo=%d&tab=chapters&chorder=asc'`

**CHANGE TO:**
`chapter_list_url = 'https://www.lightnovelworld.com/novel/%s?tab=chapters&page=%d&chorder=asc'`

**FIND:**
`page_count = int(re.findall(r'pageNo=(\d+)', last_page)[0])`

**CHANGE TO:**
`page_count = int(re.findall(r'page=(\d+)', last_page)[0])`

**Comment by dipu-bd** [comment]
@SirGryphin can you do a pull request fixing this issue?

**Comment by SirGryphin** [comment]
sent pr #721

**Comment by Galunid** [comment]
@dipu-bd Can be closed ;)
