### ISSUE TITLE
Feature Request: Add post-processing possibility

### ISSUE THREAD

**Issue by Arcansiel** [dipu-bd/lightnovel-crawler#715]
Some sources have malformed text - something like spaces before dots, a lot of trailing whitespaces or prepended whitespaces.
It would be great to have option to execute post-processing after crawler downloaded all files automatically. 

Right now it is possible by choosing json format and than executing regex (or any other way of modification) on resulting files and rerunning crawler witout re-downloading chapters to produce desired format.

Also it would be great to have ability to embed our own stylesheet into generated files - something like what [fb2Converter](https://github.com/rupor-github/fb2converter) does.

**Comment by dipu-bd** [comment]
It is not feasible to implement a common post-processing method programmatically. Because many sources have different outputs. We can make a common one by applying some NLP techniques, but I consider it outside of this project scope.

If you want to fix text formatting for specific sources, you can modify the `download_chapter_body` method. Here is an example: https://github.com/dipu-bd/lightnovel-crawler/blob/master/lncrawl/sources/boxnovelonline.py#L73
