### ISSUE TITLE
www.lightnovelworld.com isn't working

### ISSUE THREAD

**Issue by redowan99** [dipu-bd/lightnovel-crawler#748]
It only downloads first 100 chapter or chapter page 1. It doesn't crawl other chapter pages.

**Comment by Galunid** [comment]
It's already fixed in d82be416246073737a2dce4ee685b15d8b08f163

**Comment by redowan99** [comment]
It Doesn't working now. I using v2.24.1 .

**Comment by Galunid** [comment]
Yes, it will work in v2.24.2 when it's released. You can build from source if you're interested in getting it to work now. You need to use `dev` branch instead of `master` when downloading the code. See [README.md](https://github.com/dipu-bd/lightnovel-crawler#a5-run-from-source). Instead of `git clone ...` you can download the archive with the current code [here](https://github.com/dipu-bd/lightnovel-crawler/archive/dev.zip)
