### ISSUE TITLE
https://www.lunarletters.com

### ISSUE THREAD

**Issue by Stonevast** [dipu-bd/lightnovel-crawler#805]
https://www.lunarletters.com/

**Comment by SirGryphin** [comment]
Tried making source but I get this error.

` ! Error: HTTPSConnectionPool(host='www.lunarletters.com', port=443): Max retries exceeded with url: /series/living-as-the-villains-stepmother/ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1123)')))`

**Comment by dipu-bd** [comment]
Using cloudscraper was causing this issue. I changed it to normal request session. 

```
    def initialize(self):
        self.scraper = Session()
    # end def
```
