### ISSUE TITLE
Dead sources

### ISSUE THREAD

**Issue by roshavagarga** [dipu-bd/lightnovel-crawler#825]
Certain sources no longer exist or have moved:
1. 4scanlation.xyz (moved to 4scanlation.com?)
2. anythingnovel.com
3. pery.info (leads to dead wogan.info)
4. writerupdates.com
5. centinni.com

**Comment by roshavagarga** [comment]
@SirGryphin Adding you, since one of the sources at least is one you maintain :)

**Comment by SirGryphin** [comment]
@roshavagarga Thanks for letting me know, I'm not sure what the protocol / rules for removing dead sources are, I've tagged owner see what he says.

@dipu-bd What is the best way to report dead sources? is it wil bug request like this or do you remove them yourself? I'm not sure there much I can do as a contributor.

**Comment by dipu-bd** [comment]
There is currently no proper documentation to handle dead source. Let me put some info here.

You will find a `rejected_sources` variables inside the `lncrawl/sources/__init__.py` file.  To disable a source, just add it here with the reason for disabling.

Also, update the README.md. There is a rejected source section in it.

You must verify properly that the source down for all users not just for you before adding a source as rejected. There are services available for it, e.g: https://downforeveryoneorjustme.com/ 

Do not reject sources that are temporarily down for maintenance or other issues. Wait at least 2-3 weeks to see if the source is actually down for good.

**Comment by SirGryphin** [comment]
@roshavagarga

**4scanlation.xyz** 
Added to rejected, it looks like the moved site to 4scanlation.com and there is a source file for it already. It may of not worked before because 4scanlation.com was on rejected as "Site Down" but it working again so I've removed it from rejected list.

**anythingnovel.com**
Site has been down since Jan 2019 and is already on rejected list.

**pery.info** (leads to dead wogan.info)
prey/wogan as been down since january this year, I've added them to rejected.

**writerupdates.com**
Site down, check with wayback machine and it was last active in Oct 2020. I've added it to rejected.

**centinni.com**
Site is down. check with WBM, it was last online February, added it to rejected.

Changes submitted to Dev #830
