### ISSUE TITLE
Cleanup mangatoon chapter content

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#881]
Remove all left slashes  `\`  not just  ` \-`  to  `-`  or  `\"`  to  `"` . 

Because there's many double slash there.  Such as  `\\*`  will become  `\*`  or `\\(`  becomes  `\(`. 

It would be safe to remove all single left slashes. 

It won't affect the Chapter contents.

![image](https://user-images.githubusercontent.com/5158124/118803977-e54c8f00-b8c5-11eb-8aa7-d3ebcd0290ce.png)

**Comment by johnveyron** [comment]
i don't know if python supports removing single left slash or not.  otherwise you can try to removing the double left slash.  it's also probably going to remove a single left slash.

`chapter_content = [p.replace('\\', '') for p in chapter_content]`

**Comment by johnveyron** [comment]
@dipu-bd 
i don't know if python supports removing single left slash or not.  otherwise you can try to removing the double left slash.  it's also probably going to remove a single left slash.
This method works well in script, maybe even in python.

`chapter_content = [p.replace('\\', '') for p in chapter_content]`
